# Top-level Gemini API key for Streamlit
GEMINI_API_KEY = "AIzaSyDKflP19_iAKm6U2CTDV-lHZM24oxr-IwI"

[general]
project_id = "optimal-comfort-477103-q4"
location   = "us-central1"

google_credentials = """
{
  "type": "service_account",
  "project_id": "optimal-comfort-477103-q4",
  "private_key_id": "f85de994a22a6b87cb2b62b8ad8721cd2418fafa",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDKW0PvlUmHFD7m\nPITFajXLizbLVFqaRTsGldTWwqyYLF7VBxFbIICdTtoJ+vEfH59SU+CeJ9FdaGcu\n3RZkg5LK9yrC1ExwQGlZs6fWa1gIcwbGoRAKhsMY4UqJUzMclHLGmaINS7ppRvPM\nZqmNsgGzgg8GD4E7/fUN1sG5qnhsakMYLZ7zxW13sVmTu3OjVf7+awtfzNHOe+Cq\n50rsvKBLEkNcQ2CaFp+u3ua/mmmDmNiE/Fj62gwdH982+jYCigITsOkOaiXc6uU8\nZpTK7DNm9+OQPgkF7iGX+I3ImwLXinMf1m3UL+po+6ijTY3q8sTxUD3UwP6D/cF6\neUxvKCCpAgMBAAECggEAGQtIkitIyVYBHt+YkxI9DC7zniCXggZVctAyYk3/rGm5\nZuYUCNIx+MYciCWtl+uC/V5yK0DEUaotMwibz97U2RfUC/7YYwAlybtJZ2kroQgT\na5vdb2AUX0zqu6o3Zi8dMWUsQDcCICtu2vpNu8KvITdUgqyCkxkwLgFJQqBNfSVF\nGoKOWWjHmvyICsrsyobIh0u6hmpmtq6EhhydXXLX+QtsUQPxMsDT7J36k3RQqEI1\n/UrB9ay4jrZeyo/lHTVyfpLGCUYGVuIOgJlpIRiXyxjGQrUfeddr1TuN4Q2mXcBq\n1vBRlI1K/iXKW5E12Rbuk+OORK5mHBDw2fdcHjS2gQKBgQD2ZmuVAIGfIBpKreZN\nru4Yz/GJQJCvqZLvKko0uJkXlrcVpN+Ua1umdqXoqimFPnlW2t4vkqTBj6Nx0Yae\nEHzBpuY8f+9baszLOUt67EsoLrK67Ut7IYH73c3xfoeNIrAe0Pn9MzAXWM8a+FZO\nJWmlhNmsL+T0THIFqrgJFO1TGQKBgQDSPY6g8b7t4UqE7gIbFUaBNkMp/wMo5VYs\nWIaBOooQ3ekyT4LI6OH2fcHGxfia5tHbIIv1UOTVCIyCElOxyqUC8P8skiOQwNIm\nrewtQ6sFW+rZLfdgoiU0wv3aGay2RREaOPvL2O5qpFVQzgt/tPj1Ku+i1nxRmIDA\nrM8dvoH8EQKBgQCzZu0rxvuZxYD/INDPfO+FB1qAqY7vJ5OBKZRwAHwPDcBuNOZJ\nJUXM1RSFa+fhSRSF5cPidW4aNKA3jevrCGwdf4yhPjEjqYZE7YmEjalHL4EY0w+j\nLkl6/gslqw+89iWvuk5aSbvZM+NPasNEEL90MV9fnFuieEqIz71Bd4g4eQKBgEFT\nt1nzRCyOcKVVf3oC5mGIBt6pysWOXXRyHXlSQ0xyZ9+mLTFYi74X3XpyUYlwZ4z7\nVAHqHPDFM0PHhhIcsaF0WRX0YvC7uZEjQdvexulnYlYRnmh8easnW9HFYJFSbLoF\nMthok8y3O3tcSt5n0WP873FdzEteY8N67vCDHcjBAoGAZBKXTuU5IbZjul2XUcYh\njJ6W9aCijTjYIyLAzGFhfW9m+3hHRTyHreXUmV/jXRr+WnoZI8H68fW26iAt2zua\n3Aod4gZUERLPUnUCg1MMp1D8DIgcu5iPCweA936u5DJy/Obef7vq/5nFBtp2h+Lf\nY3ZW/wCF+XklTdZ9jlITnaI=\n-----END PRIVATE KEY-----\n",
  "client_email": "aaa-mvp-sa@optimal-comfort-477103-q4.iam.gserviceaccount.com",
  "client_id": "110695165292098011762",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/aaa-mvp-sa%40optimal-comfort-477103-q4.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
"""
